### ISSUE TITLE
Synchronize AX with git repo

### ISSUE THREAD

**Issue by fraga** [fraga/gitax#1]
To make this interface clean and simple, if we merge code using git, we supposed to issue the version control's sync from within AX. This would get all the xpo's in the repo folder and bring them back with 3 types of actions: add, update, delete.

**Comment by BTXAndy** [comment]
What are the steps required to get sync to work? Do we know?

**Comment by fraga** [comment]
Not 100% sure. Now I am waiting for my azure subscription to get renewed.

So far I understand current code do not fill the synchronization log correctly when you have for instance merged code or when a xpo is in the repository but not in the aot.
