### ISSUE TITLE
Assembly not referenced.

### ISSUE THREAD

**Issue by BTXAndy** [fraga/gitax#44]
Hi,

I followed all the instructions but keep getting "an Assembly containing type GTXLibGit2Sharp.GTXRepo is not referenced." error.
I have copied the whole of git bin to the client bin folder, added the gtxlibgit2sharp dll to the references in the aot etc...

Any ideas why this might not be working?

thanks

**Comment by BTXAndy** [comment]
Sorry fraga, I haven't been able to test it yet due to holidays and other commitments. Will test it today.
thanks.

**Comment by BTXAndy** [comment]
Tried it and got this error and warning in the compilation log file: 
Error \Classes\GTXPendingVCSObjects\process 53  12
Argument '_node' is incompatible with the required type.

Warning
\Classes\GTXSysVersionControlSystemMock\new  1 1
The new method of a derived class does not call super().

**Comment by fraga** [comment]
Hi @BTXAndy should be fine, I think this GTXPendingVCSObjects is not done yet

**Comment by BTXAndy** [comment]
Update: i've managed to install it on 2012 R3 RTM. I can now debug the gitax code. However, I used the latest git an libgit2 libraries and updated the code. I'll do a PR at some point when it all works for me.
In the code it says for undo checkout: //TODO: Dangerous, consider refactoring
What's it doing that is dangerous?

**Comment by fraga** [comment]
At that time I thought using FileInfo could lock the file but I learned later on that it should not be a problem but never removed the comment :)

While you're committing code to your local repository, always remember to push to your remote github repository.

**Comment by BTXAndy** [comment]
Different question: how can I add a class to a model and pick it up on another aot/machine? I've added an extra class in the repo and when I sync, it doesn't pick it up?

**Comment by fraga** [comment]
Remote syncing is not implemented yet. We must first make sure ax can sync the folder and then we implement the git part that will fetch/pull the remote branches from remote repos.

The way it is now, syncing will sync the current VCS folder and all the xpos in there. I will write in the wiki pages how to do that with the command line.

**Comment by BTXAndy** [comment]
I have a VM with a share to a repo. I added a class and committed it, then reverted to an earlier snapshot and synced. The new class didn't show up.
Remote syncing isn't required really as I use sourcetree for that and intend to use sourcetree for most git functions.
The main thing is being able to pick up code from the repo and sync the AOT with that.
Any idea why it didn't pick up the new class?

**Comment by BTXAndy** [comment]
ok, I think I figured how to do it: 
synchronize forced
restart client.
Is that the normal way to sync the AOT and client with the local repo?

**Comment by fraga** [comment]
We are probably missing something in order to make it work without "forcing" it

If you want you can create another issue so we track the progress while fixing it

**Comment by BTXAndy** [comment]
Sorry to add more to this issue, but didn't know where to put it.
To fix the referencing issue, I updated libgit and libgit2sharp to the latest at the time, referenced them in the .NET project and updated the project file to copy them to the client bin folder during build.
This works fine, except that you need to import the attached xpo twice for some reason.
However, I can't get  AX to sync up to 2 models I already have in git. These were added to AX on another machine.
History etc works, but sync doesn't seem to do anything.
How can I send you the XPO file?

**Comment by fraga** [comment]
You can send to my email along with details of what you are experiencing :)

**Comment by BTXAndy** [comment]
sure thanks, but what's your email address?

**Comment by fraga** [comment]
Check on the commits my email is there :)

**Comment by BTXAndy** [comment]
Now there's an idea! :)
Will send xpo tomorrow morning with more info. Thanks.

**Comment by fraga** [comment]
Ok looking forward to it :)

Will close this issue if you dont mind

Ttyl
