### ISSUE TITLE
file structure reflecting AX layer structure

### ISSUE THREAD

**Issue by weedgarden** [fraga/gitax#46]
Hi Rodrigo,
thanks for your work at gitax.
Anyway, as I think about using git with AX, I find using model-based versioning insufficient:
- When overloading single method of a class from another model (or lower layer? srry .. not sure), I have to move whole the class to one model to be able to use VC.
- I also can't version the changes in other layers - if update or external contractor changes behaviour of lower layer class, I won't even noticed it

Would it be useful to reimplement the file structure to reflect layer structure of AOT?
Or do you have other solution for such an issue?

**Comment by fraga** [comment]
hi @weedgarden 
thanks for your comments. Can't really answer right now but will do my best to answer by EOD

**Comment by weedgarden** [comment]
thanks for immediate readction, I'm looking forward to your answer
as I tried using gitax little more, I found the first bullet is not an issue:
- when overriding method of a lower layer class, xpo generated from the class contains changes in current layer only
- when overriding method of a class from another model, I simply switch to that model or move whole the class to one model, xpo generated again contains this layer changes only

**Comment by fraga** [comment]
I think we should have a better repro step for the second bullet.

is this 'another model' a foundation model or custom model?

**Comment by weedgarden** [comment]
sorry, I wrote my second post not that clearly I thought: I wrote about the first bullet of my original question - these two bullets at the second post are just the solution I found for the first issue

well, now there remains just the bullet discussing how to version changes in lower layers

**Comment by fraga** [comment]
@weedgarden let me get my azure vm back and we're going to work on that too

**Comment by fraga** [comment]
Hi @weedgarden sorry for taking too long to answer your question

If you don't add the model to the version control, when you add the AOT object to the version control it should add the object into the layerfolder/AOTtype/FileName.xpo, example:

1) Create new job called Excel
2) Add to the version control in 
3) Check it will add a new file in c:\yourrepositoryfolder\usr\Jobs\Excel.xpo

I think this answer your question, let me know if I can close this issue

**Comment by weedgarden** [comment]
Hi @fraga 
Thanks for your answer.
I didn't know about possibility to add an AOT object to VC without model versioning, so thanks you clarified me that. Anyway as I tried to version e.g. AbatementCertificate_IN (sys layer, Foundation model) I got an error message:
*\Classes\AbatementCertificate_IN can't be added to version control as it does not exists in usr layer*
As far as I know it could be limitation of the licence my company has.
The goal of this question was to be able to version also code changes from lower layer - changes of external contractors or MS itself (patches, service packs etc.).
If you don't know about other solution, please, treat this question as closed.

**Comment by fraga** [comment]
Yeah @weedgarden you really can't add to version control an item that is not in your current layer.

You really don't want to control others code, it makes harder to maintain your own code.

Tks
