### ISSUE TITLE
Argument '_node' is incompatible with the required type. 

### ISSUE THREAD

**Issue by BTXAndy** [fraga/gitax#47]
After building with axbuild, I get this error and I can't figure out how to fix it:
Error \Classes\GTXPendingVCSObjects\process 53 12 Argument '_node' is incompatible with the required type. 

Any ideas?

**Comment by fraga** [comment]
Yeah just ignore it for the time being it hasnt been implemented

**Comment by BTXAndy** [comment]
Could I comment this out for the time being? I'm trying to get a clean compile.
  if(versionControl.allowCreate(controlable))
        {
            //do something if it isn't in version control
            info(strfmt("%1\t%2",pNode.treeNodeType(), pNode.treeNodeName()));
        }

**Comment by fraga** [comment]
Yep go ahead and comment :)
