### ISSUE TITLE
Overview_GTXFileRepoStatus has not been declared.	

### ISSUE THREAD

**Issue by BTXAndy** [fraga/gitax#48]
I'm also getting these 2 errors. Any ideas?

Variable Overview_GTXFileRepoStatus has not been declared.	\Forms\SysVersionControlCheckedOut\Methods\init	38	init	Err:9	

Variable ModifiedBy_GTXSha has not been declared.	\Forms\SysVersionControlItemHistory\Methods\init	35	init	Err:9

**Comment by fraga** [comment]
Did you take this code from the latest model ?

Well is it when compiling x++ or cil?

**Comment by BTXAndy** [comment]
Yes/No :) . It comes from the latest model imported into R3 then exported to xpo and imported into 2012 CU1. Then exported to a model and imported back into R3.
I'm trying to get model which will work with any version of 2012. If not, as few models as possible. Background is that we have a product that works on all versions of AX.
I'm doing a full compile using AXBuild on the original R3 again as I suspect I did not check the log files at the time.

**Comment by fraga** [comment]
Got it

If you want we can schedule a meeting and talk about this issue and the
others and anything else to make this work for you.

You can contact me directly in my email.

**Comment by BTXAndy** [comment]
Just had the results back and only the earlier _node issue was there. Clearly something went wrong in trying to make it run on 2012RTM. Will investigate further.
What timezone are you in?

**Comment by fraga** [comment]
EST

**Comment by fraga** [comment]
Let me know @BTXAndy if you have more issues. Will close this issue for now, you can reopen if needed.
