### ISSUE TITLE
getting err msg @SYS343905 when trying to delete VS project

### ISSUE THREAD

**Issue by weedgarden** [fraga/gitax#49]
1) VS: create VS project (Visual C# -> Windows project)
2) VS: add to AOT, build, deploy
3) AX2012: add VS project to version control
4) commit
5) AX2012: delete the VS project
I got @SYS343905 (The project cannot be deleted because %1 is checked out.) when trying the last step.
No pending objects. "Undo checkout" does not help.
Did I understood something wrong or made a mistake? Or is this relevant to your last comment in #1 ? Thanks for your reply.

**Comment by fraga** [comment]
Hey

I believe adding VS project is still really unstable as it is a folder and
its treated differently.

Same to other items that usually creates a folder under the model folder.

It needs more investigation on how to correcly implement undo checkout

**Comment by fraga** [comment]
hi @weedgarden did you make any progress on this issue?

I'm running into some azure problems and my VM is not available, probably in a few days then we can work together on that

**Comment by fraga** [comment]
Hi @weedgarden I am going to close this issue and create a new one as a feature
